name: PromptFileLoader


on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release  # Use the environment you created

    permissions:
      contents: read
      packages: write
      id-token: write  # Needed for OIDC token

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade build twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          No need for API token here, OIDC handles auth
          If you want to use API token instead, set pypi_token secret and uncomment below:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
